-- 코드를 작성해주세요
SELECT FISH_INFO.ID, FISH_NAME_INFO.FISH_NAME AS FISH_NAME, FISH_INFO.LENGTH AS LENGTH
FROM FISH_INFO JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE (FISH_INFO.FISH_TYPE, FISH_INFO.LENGTH) IN 
    (SELECT FISH_INFO.FISH_TYPE, MAX(FISH_INFO.LENGTH)
     FROM FISH_INFO
     GROUP BY FISH_INFO.FISH_TYPE)
ORDER BY FISH_INFO.ID;